### ISSUE TITLE
trao+nutui小程序图标不显示，H5正常，能否按照Trao+TraoUI修复下？

### ISSUE THREAD

**Issue by Baiyuetribe** [jdf2e/nutui-demo#1]
H5效果如下：
![image](https://user-images.githubusercontent.com/43716063/116807788-a9949400-ab67-11eb-8ce4-e54588bc2e8a.png)
小程序凡是带图标的都异常
![image](https://user-images.githubusercontent.com/43716063/116808007-080e4200-ab69-11eb-9526-473bf345d683.png)

已实现案例：
https://github.com/b2nil/taro-ui-vue3/
上述方案实现了taro-ui+vue3，小程序和H5均正常

**Comment by richard1015** [comment]
由于Button组件内部图标依赖 Icon ,需使用下方使用方式

``` import { Button,Icon } from '@nutui/nutui-taro';```

下个版本文档将更新
