### ISSUE TITLE
nutui-vue/taro项目运行报错

### ISSUE THREAD

**Issue by muyugbl** [jdf2e/nutui-demo#14]
我使用yarn安装完依赖后，运行yarn dev:weapp命令，报错提示： 全局配置缺少 pages 字段，请检查

<img width="1018" alt="1688605715260" src="https://github.com/jdf2e/nutui-demo/assets/33854170/bb8a59e8-bb85-4023-bf3f-7ca67972628b">

**Comment by tjw-javen** [comment]
升级依赖版本到"@tarojs/webpack5-runner": "^3.6.8"  亲测有效
