### ISSUE TITLE
nut-ui有支持uniapp的计划么？

### ISSUE THREAD

**Issue by Damocs0921** [jdf2e/nutui-demo#9]
https://github.com/jdf2e/nutui-demo/tree/master/uniapp-vue3

**Comment by zhangchenna** [comment]
> https://github.com/jdf2e/nutui-demo/tree/master/uniapp-vue3

里面完全没有关于nutui的东西

**Comment by richard1015** [comment]
https://github.com/jwaterwater/uni-nutui
